
name: Deploy

on:
  push:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build-hugo:
    name: Deploy on gh-pages
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v4
      with:
        go-version: 1.21.6
      id: go
    
    - name: Install Dart Sass
      run: sudo snap install dart-sass

    - name: Install Hugo
      run: sudo snap install hugo

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Build Hugo
      run: hugo

    - name: Copy CNAME
      run: cp ./CNAME public/

    - name: Deploy branch
      uses: s0/git-publish-subdir-action@develop
      env:
        REPO: git@github.com:snapsite-xyz/snapsite-xyz.github.io.git
        BRANCH: gh-pages
        FOLDER: public
        SSH_PRIVATE_KEY: ${{ secrets.DEPLOY_PRIVATE_KEY }}
